name: 'ci'

on:
  push:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      -
        name: Install
        run: go get dagger.io/dagger@latest cloud.google.com/go/run/apiv2
      -
        name: Release and deploy with Dagger
        run: go run main.go
